### ISSUE TITLE
Custom World Pocket Dimension

### ISSUE THREAD

**Issue by xxswagmonster58** [RafalBerezin/Pocket_Dimension#3]
I would love to see the ability to disable the worldgen in this datapack to allow the use of custom worldgens or simply drop in worlds to have as the pocket dimension. This way I could implement new structures and adventures to my players without having to create a new world and restarting. I really love this datapack, but I want to use it this way, if that is at all possible.

**Comment by RafalBerezin** [comment]
Alright so,

I won't be doing that in the data pack, but if you want to try to figure it out, then I can give you some tips. Just keep in mind that **I haven't tested any of this**, so I'm basically guessing. (Also, I'm pretty sure you need to restart the world or server after changing any of this)

## Disable or modify worldgen

Pocket Dimension already doesn't generate anything inside, so you can just change the biome or whatever you want. The portal platform is generated by the function [data/pocket_dimension/functions/effects/portal/entrance/teleport.mcfunction](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/effects/portal/entrance/teleport.mcfunction) so you can just remove the (line 9) `place jigsaw pocket_dimension:portal_platform minecraft:empty 1`.

If you want a custom worldgen, then you should try changing the contents of

[data/pocket_dimension/dimension/pocket_dimension.json](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/dimension/pocket_dimension.json)
[data/pocket_dimension/dimension_type/pocket_dimension.json](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/dimension_type/pocket_dimension.json)
etc.

You can play around with the setting [HERE](https://misode.github.io/dimension/)

## Adding a custom world

I guess you could replace the contents of `<world>/dimensions/pocket_dimension/pocket_dimension/` with the same kind of stuff from a different world.

Keep in mind that you need to either pre-generate the world that you want to put in there or set the correct worldgen settings for pocket_dimension.

## Other

If you want to teleport everyone to some specific location, then you can modify the [data/pocket_dimension/functions/portal/entrance/create.mcfunction](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/portal/entrance/create.mcfunction) like this:
- `execute store result storage pocket_dimension:main root.portal.destination.x int 0.01 run data get entity @s UUID[0]` -> `data modify storage pocket_dimension:main root.portal.destination.y set value X_VALUE` (line 10)
- `data modify storage pocket_dimension:main root.portal.destination.y set value 0` -> `data modify storage pocket_dimension:main root.portal.destination.y set value Y_VALUE` (line 5)
- `execute store result storage pocket_dimension:main root.portal.destination.x int 0.01 run data get entity @s UUID[0]` -> `data modify storage pocket_dimension:main root.portal.destination.y set value Z_VALUE` (line 11)

But everyone will exit to the same place, as the portal in the return position will be replaced every time someone enters.

Also, to prevent players from teleporting into a wall, you can change (line 8) `tp ~ ~ ~`  in [data/pocket_dimension/functions/effects/portal/entrance/teleport.mcfunction](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/effects/portal/entrance/teleport.mcfunction) to `execute positioned over motion_blocking run tp ~ ~ ~`. This will move the teleportation position to over the highest block of the world in these specific XZ coordinates.

---

Since I'm not working on it, I'm going to close this issue. But if you have some more questions, feel free to ask them here.

**Comment by xxswagmonster58** [comment]
I really appreciate the tips! Now, I don't want to sound like I'm trying to steal your work, but is there a way to essentially duplicate the datapack to make different tesseracts for different worlds? I want to keep the original and have a few others to occasionally incorporate into my server so my players have something new to explore once in a while. I'm just not sure how much of the datapack will have to have names altered and whatnot.

**Comment by RafalBerezin** [comment]
Feel free to modify the code however you like. Download it locally, fork the project on Github, or do whatever you really prefer. Just keep the [LICENSE](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/LICENSE) with the original copyright notice. Also, if you decide to distribute the modified version, it's nice to state that you modified it, but that's not required by the license I used.

If you want to create new items, just do it the same way I did it [HERE](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/loot_tables/items/dimensional_tesseract.json).
If you also want a recipe for them then look into: [recipes](https://github.com/RafalBerezin/Pocket_Dimension/tree/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/recipes), [these advancements](https://github.com/RafalBerezin/Pocket_Dimension/tree/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/advancements/utils/crafting) and [these functions](https://github.com/RafalBerezin/Pocket_Dimension/tree/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/crafting)

And then you can just add one line of code [HERE](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/items/main.mcfunction) to run a different function when the player holds your new item. You can work off of [THIS](https://github.com/RafalBerezin/Pocket_Dimension/blob/33e5fbd23ba8efa7be760c8f4a2fab95bcbd2530/Pocket_Dimension_DAT/data/pocket_dimension/functions/items/dimensional_tesseract/main.mcfunction) function that's run when holding the Dimensional Tesseract.

Also, for Minecraft 1.20.5+, this data pack will be built using [Arcane Core](https://github.com/RafalBerezin/Arcane_Core). I plan to release it soon. Maybe you'd like to use that as well.
